export const enum SubnetCalculationInitialCombinations {
  AddressAndSubnetMask,
  AddressAndSubnetMaskBits,
  SubnetAddressAndSubnetMaskAndMachineNumber,
  SubnetAddressAndSubnetMaskBitsAndMachineNumber,
  MainNetAndSubnetMaskAndSubnetNumberAndMachineNumber,
  MainNetAndSubnetMaskBitsAndSubnetNumberAndMachineNumber,
  MainNetAndSubnetNumberAndMinNumberOfMachinesParSubnetAndMachineNumber,
  MainNetAndSubnetNumberAndMinNumberOfSubnetsAndMachineNumber,
}
